repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-json
      - id: check-case-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: check-symlinks
      - id: check-yaml
      - id: detect-private-key
      - id: forbid-new-submodules
      - id: check-docstring-first

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.15.0'
    hooks:
      - id: mypy
        args: [ --strict, --ignore-missing-imports, --allow-untyped-decorators, --allow-subclassing-any ]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.5
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        language: python
        args: [ --in-place, --black ]
  - repo: https://github.com/Carreau/velin
    rev: 0.0.12
    hooks:
      - id: velin
        args: [ --write ]
